Name Entity Recognition

In [2]:
sentence = "Mount Everest lies in Nepal and Gautam Buddha was born in Nepal"
"""
Person: Nabin
Place or Location: Kathmandu
Date: June 6
Time: 2:13 PM
money: 100
Organization: Mindrisers
Percent : 20%, Twenty percent
"""

'\nPerson: Nabin\nPlace or Location: Kathmandu\nDate: June 6\nTime: 2:13 PM\nmoney: 100\nOrganization: Mindrisers\nPercent : 20%, Twenty percent\n'

In [3]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |  

True

In [4]:
words = nltk.word_tokenize(sentence)

In [5]:
words

['Mount',
 'Everest',
 'lies',
 'in',
 'Nepal',
 'and',
 'Gautam',
 'Buddha',
 'was',
 'born',
 'in',
 'Nepal']

In [6]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [7]:
nltk.download('maxent_ne_chunker_tab')

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!


True

In [8]:
nltk.download('words')

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [9]:
elements = nltk.pos_tag(words)# pos --> Part of Speech

In [10]:
elements

[('Mount', 'NNP'),
 ('Everest', 'NNP'),
 ('lies', 'VBZ'),
 ('in', 'IN'),
 ('Nepal', 'NNP'),
 ('and', 'CC'),
 ('Gautam', 'NNP'),
 ('Buddha', 'NNP'),
 ('was', 'VBD'),
 ('born', 'VBN'),
 ('in', 'IN'),
 ('Nepal', 'NNP')]

In [11]:
#nltk.ne_chunk(elements).draw() on juypter notebook

POS(Part of Speech) Tagging


  *   Gautam Buddha was born in Nepal



In [12]:
paragraph="""Nepal is a small, landlocked country located between India and China in South Asia. It is known for its rich cultural heritage, diverse geography, and friendly people. The country is home to the majestic Himalayas, including Mount Everest, the highest peak in the world. Nepal’s landscape ranges from lush green plains in the south to snow-capped mountains in the north. Kathmandu, the capital city, is famous for its ancient temples, stupas, and vibrant traditions. Despite being a developing nation, Nepal attracts millions of tourists each year for trekking, mountaineering, and spiritual exploration."""

In [13]:
import nltk
sentences = nltk.sent_tokenize(paragraph)

In [14]:
sentences

['Nepal is a small, landlocked country located between India and China in South Asia.',
 'It is known for its rich cultural heritage, diverse geography, and friendly people.',
 'The country is home to the majestic Himalayas, including Mount Everest, the highest peak in the world.',
 'Nepal’s landscape ranges from lush green plains in the south to snow-capped mountains in the north.',
 'Kathmandu, the capital city, is famous for its ancient temples, stupas, and vibrant traditions.',
 'Despite being a developing nation, Nepal attracts millions of tourists each year for trekking, mountaineering, and spiritual exploration.']

Stopwords

In [15]:
from nltk.corpus import stopwords

In [16]:
len(sentences)

6

In [17]:
nltk.pos_tag(sentences)#POS sentence wise

[('Nepal is a small, landlocked country located between India and China in South Asia.',
  'NNP'),
 ('It is known for its rich cultural heritage, diverse geography, and friendly people.',
  'NNP'),
 ('The country is home to the majestic Himalayas, including Mount Everest, the highest peak in the world.',
  'NNP'),
 ('Nepal’s landscape ranges from lush green plains in the south to snow-capped mountains in the north.',
  'NNP'),
 ('Kathmandu, the capital city, is famous for its ancient temples, stupas, and vibrant traditions.',
  'NNP'),
 ('Despite being a developing nation, Nepal attracts millions of tourists each year for trekking, mountaineering, and spiritual exploration.',
  'NNP')]

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [20]:
for i in range(len(sentences)):
  words = nltk.word_tokenize(sentences[i])
  words = [word for word in words if word not in  set(stopwords.words('english'))]
  pos_tag = nltk.pos_tag(words)
  print(pos_tag)

[('Nepal', 'NNP'), ('small', 'JJ'), (',', ','), ('landlocked', 'JJ'), ('country', 'NN'), ('located', 'VBD'), ('India', 'NNP'), ('China', 'NNP'), ('South', 'NNP'), ('Asia', 'NNP'), ('.', '.')]
[('It', 'PRP'), ('known', 'VBD'), ('rich', 'JJ'), ('cultural', 'JJ'), ('heritage', 'NN'), (',', ','), ('diverse', 'JJ'), ('geography', 'NN'), (',', ','), ('friendly', 'JJ'), ('people', 'NNS'), ('.', '.')]
[('The', 'DT'), ('country', 'NN'), ('home', 'NN'), ('majestic', 'JJ'), ('Himalayas', 'NNP'), (',', ','), ('including', 'VBG'), ('Mount', 'NNP'), ('Everest', 'NNP'), (',', ','), ('highest', 'JJS'), ('peak', 'JJ'), ('world', 'NN'), ('.', '.')]
[('Nepal', 'NNP'), ('’', 'NNP'), ('landscape', 'NN'), ('ranges', 'VBZ'), ('lush', 'JJ'), ('green', 'JJ'), ('plains', 'NNS'), ('south', 'JJ'), ('snow-capped', 'JJ'), ('mountains', 'NNS'), ('north', 'RB'), ('.', '.')]
[('Kathmandu', 'NNP'), (',', ','), ('capital', 'NN'), ('city', 'NN'), (',', ','), ('famous', 'JJ'), ('ancient', 'NN'), ('temples', 'NNS'), (',', 

In [21]:
"Gautam Buddha was vorn in Nepal".split()

['Gautam', 'Buddha', 'was', 'vorn', 'in', 'Nepal']

In [22]:
for i in "Gautam Buddha was vorn in Nepal".split():
  print(nltk.pos_tag([i]))

[('Gautam', 'NN')]
[('Buddha', 'NN')]
[('was', 'VBD')]
[('vorn', 'NN')]
[('in', 'IN')]
[('Nepal', 'NN')]


Sentiment Analysis

Text---------------------Output
*   The food is good.---->1

*   the food is Bad.---->0
*   Pizza is amazing.---->1


*   Burger is bad.---->0



Dataset
  Text Preprocessing(1)


*   Tokenization
*   Lowercase

*   Regular Expression

Text Preprocessing(2)


*   Stemming

*   Lemmatization
*   Stopwords Removal
Text------> Vector
*   One Hot Encoding(OHE)
*   Bag of Words(BOW)
*   TFIDF


ML Algorithm











*   OHE is a way to convert words into numbers.
['Cat','Dog','Cow']


*   Word-----OHE

*   Cat------[1,0,0]

*   Dog------[0,1,0]
*   Cow------[0,0,1]

Advantage:


  *   Easy to implement with Python.(sklearn one hote encoder)

Disadvantages:


  *   Sparse Matrix--> Overfitting
  *   No fixed size input.

  *   Sementic meaning is not captured.










BOW(Bag of Words)


*   Text -------------- Output
*   He is a good boy      1

*   She is a good girl    1
*   Boy and girl are good 1



Lowercase + Stopwords Removal



  *   s1--->good boy

  *   s2---> good girl
  *   s3---> boy girl good




*   Vocabulary---Frequency

  *   good--------3

  *   boy---------2

  *   girl--------2



*   good--boy--girl
*   1-----1----0
*   1----0-----1
*   1----1-----1


Advantage:
  *   Simple

  *   Fized size input
  
Disadvantage
  *   Sparse matrix---> Overfitting.
  *   Ordering of words change.
  *   Out of vocabulary.





In [24]:
import pandas as pd
messages = pd.read_csv('sms.csv',index_col = 0)


In [25]:
message

NameError: name 'message' is not defined

In [26]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [27]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [28]:
ps = PorterStemmer()

In [29]:
re.sub('[^a-zA-Z]',' ','This is the 2nd time we have tried 2 contact').lower().split()

['this', 'is', 'the', 'nd', 'time', 'we', 'have', 'tried', 'contact']

In [30]:
corpus= []
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['text'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


In [31]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500)

In [33]:
X = cv.fit_transform(corpus)

In [34]:
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 40417 stored elements and shape (5572, 2500)>

In [35]:
X =X.toarray()

In [36]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [37]:
X.shape

(5572, 2500)

In [38]:
cv = CountVectorizer(max_features=100,binary = True)
x = cv.fit_transform(corpus).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [39]:
x.shape

(5572, 100)

In [40]:
vocabulary = cv.vocabulary_
vocabulary

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(90),
 'ok': np.int64(56),
 'free': np.int64(18),
 'win': np.int64(94),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(67),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(73),
 'send': np.int64(69),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(62),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(47),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(82),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(64),
 'www': np.int64(96),
 'right': np.int64(65),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'use': np.int64(87),
 'messag': np.int64(44),
 'oh': np.int64(55),
 'ye': np.int64(97),
 'make': np.int64(42),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(14

In [41]:
cv = CountVectorizer(max_features= 100,binary = True, ngram_range=(1,3))
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [42]:
vocabulary = cv.vocabulary_
vocabulary

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(91),
 'ok': np.int64(57),
 'free': np.int64(18),
 'win': np.int64(95),
 'text': np.int64(78),
 'txt': np.int64(86),
 'say': np.int64(68),
 'alreadi': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(28),
 'week': np.int64(93),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(74),
 'send': np.int64(70),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(63),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(48),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(90),
 'today': np.int64(83),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(65),
 'www': np.int64(97),
 'right': np.int64(66),
 'thank': np.int64(79),
 'take': np.int64(76),
 'time': np.int64(82),
 'use': np.int64(88),
 'messag': np.int64(45),
 'oh': np.int64(56),
 'ye': np.int64(98),
 'make': np.int64(43),
 'way': np.int64(92),
 'feel': np.int64(16),
 'dont': np.int64(14

In [43]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

TF-IDF(Term Frequency - Inverse Document Frequency)


* S1-->good boy
* S2-->good girl
*  S3-->boy girl good



*   TF = No.of repetition of words in sentence/No. of words in sentence
*   IDF = Loge(No. of sentences/ No. of sentences containing that word)



ADV


*   Word importance captured.
*   Fixed size input.

Disadvantage

*   Sparsity exist Out of vocabulary







TF-IDF

In [44]:
import pandas as pd
message = pd.read_csv('sms.csv',index_col = 0)

In [45]:
messages

target                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham            Will �_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [46]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [47]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [48]:
corpus = []
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['text'][i])
  review = review.lower()
  review = review.split()
  review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [49]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=100)
X = tfidf.fit_transform(corpus).toarray()

In [51]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [52]:
import numpy as np
np.set_printoptions(edgeitems = 30,linewidth=100000)

In [53]:
X

array([[0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.43475457, 0.        , 0.        , 0.46143072, 0.5437127 , 0.        , 0.        , 0.        , 0.        , ..., 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.54995151, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.    

In [54]:
tfidf.vocabulary_

{'go': np.int64(21),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(89),
 'ok': np.int64(58),
 'free': np.int64(17),
 'win': np.int64(93),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(68),
 'already': np.int64(0),
 'think': np.int64(80),
 'life': np.int64(37),
 'hey': np.int64(28),
 'week': np.int64(91),
 'back': np.int64(5),
 'like': np.int64(38),
 'still': np.int64(73),
 'send': np.int64(70),
 'friend': np.int64(18),
 'prize': np.int64(63),
 'claim': np.int64(8),
 'call': np.int64(6),
 'mobile': np.int64(48),
 'co': np.int64(9),
 'home': np.int64(30),
 'want': np.int64(88),
 'today': np.int64(82),
 'cash': np.int64(7),
 'day': np.int64(13),
 'reply': np.int64(65),
 'www': np.int64(96),
 'right': np.int64(66),
 'take': np.int64(75),
 'time': np.int64(81),
 'message': np.int64(45),
 'com': np.int64(10),
 'oh': np.int64(57),
 'yes': np.int64(99),
 'make': np.int64(43),
 'way': np.int64(90),
 'dont': np.int64(15),
 'miss': np.int64(47),
 'ur': np.int64(87

In [55]:
tfidf = TfidfVectorizer(max_features=100, ngram_range=(2,2))
x = tfidf.fit_transform(corpus).toarray()

In [56]:
tfidf.vocabulary_

{'free entry': np.int64(32),
 'claim call': np.int64(16),
 'call claim': np.int64(3),
 'free call': np.int64(31),
 'chance win': np.int64(15),
 'txt word': np.int64(88),
 'let know': np.int64(52),
 'please call': np.int64(64),
 'lt gt': np.int64(56),
 'want go': np.int64(97),
 'like lt': np.int64(53),
 'sm ac': np.int64(78),
 'sorry call': np.int64(79),
 'call later': np.int64(9),
 'ur awarded': np.int64(90),
 'call free': np.int64(5),
 'hi hi': np.int64(45),
 'call customer': np.int64(4),
 'customer service': np.int64(23),
 'cash prize': np.int64(14),
 'trying contact': np.int64(85),
 'draw show': np.int64(28),
 'show prize': np.int64(76),
 'prize guaranteed': np.int64(70),
 'guaranteed call': np.int64(41),
 'valid hr': np.int64(95),
 'selected receive': np.int64(73),
 'private account': np.int64(68),
 'account statement': np.int64(0),
 'statement show': np.int64(80),
 'call identifier': np.int64(6),
 'identifier code': np.int64(48),
 'code expires': np.int64(20),
 'urgent mobile': np